import type { Photo } from "./types";

/** Generated by scripts/fetch-photos.mjs from Wikimedia Commons. */
export const photos: Photo[] = [
  {
    "file": "hero-plaza-dusk.jpg",
    "title": "Blue hour at the plaza entrance",
    "author": "Gostsens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Z%C3%BCrich..jpg",
    "width": 1333,
    "height": 2000
  },
  {
    "file": "from-hardbruecke.jpg",
    "title": "From Bahnhof Hardbrücke",
    "author": "Hauserphoton",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Z%C3%BCrich.jpg",
    "width": 1125,
    "height": 2000
  },
  {
    "file": "kaeferberg-evening.jpg",
    "title": "Evening light from Käferberg",
    "author": "Roland zh",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Z%C3%BCrich_-_K%C3%A4ferberg-Waidspital_2016-05-17_18-55-57.JPG",
    "width": 1333,
    "height": 2000
  },
  {
    "file": "low-angle-sunny.jpg",
    "title": "Green glass against blue sky",
    "author": "Fred Romero from Paris, France",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Z%C3%BCrich_-_Prime_Tower_(48677546201).jpg",
    "width": 1333,
    "height": 2000
  },
  {
    "file": "aerial-2023.jpg",
    "title": "Drone aerial over Zürich-West, 2023",
    "author": "Daniel Reust",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Luftaufnahme,_2023.jpg",
    "width": 2000,
    "height": 1125
  },
  {
    "file": "aerial-2011.jpg",
    "title": "Aerial view amid the railway yards, 2011",
    "author": "Hansueli Krapf  This   file was uploaded  with Commonist.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Zurich.JPG",
    "width": 1328,
    "height": 2000
  },
  {
    "file": "top-alps-bluehour.jpg",
    "title": "Lit upper floors against the Alps",
    "author": "kuhnmi",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:DSC_2727_3_(11806742154).jpg",
    "width": 2000,
    "height": 1073
  },
  {
    "file": "night-entrance.jpg",
    "title": "Entrance canopy and lobby glow at night",
    "author": "FreeclimbZurich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Night_Entrance.jpg",
    "width": 2000,
    "height": 1334
  },
  {
    "file": "night-elevated.jpg",
    "title": "Night view with Hardbrücke",
    "author": "FreeclimbZurich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Night_Z%C3%BCrich_Zurich.jpg",
    "width": 2000,
    "height": 1334
  },
  {
    "file": "facade-lookup.jpg",
    "title": "Straight up the glass grid",
    "author": "Marius Haffner from Grenchen, Schweiz",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower,_Z%C3%BCrich_(24209383652).jpg",
    "width": 2000,
    "height": 1333
  },
  {
    "file": "cantilever-evening.jpg",
    "title": "Upper volumes and cantilevers, 2011",
    "author": "Roland zh",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Industriequartier_-_Prime_Tower_-_Hardbr%C3%BCcke_Bahnhof_2011-09-06_19-48-02.JPG",
    "width": 1328,
    "height": 2000
  },
  {
    "file": "reflection.jpg",
    "title": "Reflected in the neighbouring facade",
    "author": "Wendelin Jacober",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Z%C3%BCrich_Prime_Tower.jpg",
    "width": 1327,
    "height": 2000
  },
  {
    "file": "cubus-annex.jpg",
    "title": "The Cubus annex with the tower behind",
    "author": "Gostsens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_Cubus_in_Z%C3%BCrich.jpg",
    "width": 1333,
    "height": 2000
  },
  {
    "file": "viaduct-arch.jpg",
    "title": "Framed by the railway viaduct",
    "author": "Tschubby",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_2020.JPG",
    "width": 1429,
    "height": 2000
  },
  {
    "file": "snowfall.jpg",
    "title": "Snowfall on the Maag site, 2021",
    "author": "Thomas Woodtli from Zürich, Switzerland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Prime_Tower_bei_Schneefall_-_Z%C3%BCrich_(50841680992).jpg",
    "width": 1500,
    "height": 2000
  },
  {
    "file": "maagplatz-cubus.jpg",
    "title": "From Maagplatz with the Cubus",
    "author": "Roy Egloff",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:CH.ZH.Zurich_2014-05-31_Prime-Tower.jpg",
    "width": 2000,
    "height": 1333
  },
  {
    "file": "view-from-top.jpg",
    "title": "View from the tower toward Uetliberg",
    "author": "Paebi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Z%C3%BCrich_vom_Prime_Tower.jpg",
    "width": 2000,
    "height": 1415
  }
];
